spring.application.name=clickrush
spring.datasource.url=jdbc:postgresql://localhost:5432/clickrush
spring.datasource.username=postgres
spring.datasource.password=Yashwin@777
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.security.user.password=Yashwin@777